# render.yaml
services:
  - type: web
    name: nomba-backend
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: nomba-db
          property: connectionString
      - key: APP_MODE
        value: "test"
databases:
  - name: nomba-db
    plan: free
