// services/errorClassifier.js

const ERROR_CATEGORIES = {
    TRANSIENT_NETWORK: 'TRANSIENT_NETWORK',
    GATEWAY_DOWN: 'GATEWAY_DOWN',
    INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
    HARD_FAILURE: 'HARD_FAILURE'
};

const classifyError = (errorCode) => {
    // Mapping hypothetical Nomba API codes to internal categories
    const mappings = {
        'NETWORK_TIMEOUT': ERROR_CATEGORIES.TRANSIENT_NETWORK,
        'CONN_RESET': ERROR_CATEGORIES.TRANSIENT_NETWORK,
        'GATEWAY_UNAVAILABLE': ERROR_CATEGORIES.GATEWAY_DOWN,
        'MAINTENANCE_MODE': ERROR_CATEGORIES.GATEWAY_DOWN,
        'INSUFFICIENT_FUNDS': ERROR_CATEGORIES.INSUFFICIENT_FUNDS,
        'EXPIRED_CARD': ERROR_CATEGORIES.HARD_FAILURE,
        'INVALID_CARD': ERROR_CATEGORIES.HARD_FAILURE
    };

    return mappings[errorCode] || ERROR_CATEGORIES.HARD_FAILURE;
};

module.exports = { classifyError, ERROR_CATEGORIES };
